### ISSUE TITLE
Cuadro Comparativo-Nancy Os

### ISSUE THREAD

**Issue by Nancy-0714** [SistemasTecTlaxiaco/actividad-3-cuadro-comparativo-Nancy-0714#1]
Actividad 3.
Nancy Olivera Santiago.
Grupo:1BS

[Metodo Cientifico-Nancy Olivera Santiago.pdf](https://github.com/SistemasTecTlaxiaco/actividad-3-cuadro-comparativo-Nancy-0714/files/9458522/Metodo.Cientifico-Nancy.Olivera.Santiago.pdf)

**Comment by Nancy-0714** [comment]
https://youtu.be/S7Xt4XM1f1w

De aquí saque mi información profe.☝🏼

**Comment by Daisy-GonzalezLita12** [comment]
14.2

**Comment by josealfredo79** [comment]
Revisado...
